#!/bin/sh

# Dependency: Inkscape, dmenu

# Options and variables
while getopts ":d:n:p:h" o; do
    case "${o}" in
	h) printf '%s\n' "Arguments:" "-d: Specify project directory" "-n: Specify imgname" "-p: use menu system other than dmenu" && exit ;;
	d) DIR=${OPTARG} ;;
	n) imgname=${OPTARG} ;;
	p) prog=${OPTARG} ;;
	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit ;;
    esac
done

svg2pdf () {
    inkscape --export-dpi 1200 "$1.svg" --export-area-drawing --export-latex --export-type=pdf --export-filename "$1.pdf"
}

template () {
    printf '%s\n' \
	'<?xml version="1.0" encoding="UTF-8" standalone="no"?>' \
	'<!-- Created with Inkscape (http://www.inkscape.org/) -->' \
	'<svg' \
	'   xmlns:dc="http://purl.org/dc/elements/1.1/"' \
	'   xmlns:cc="http://creativecommons.org/ns#"' \
	'   xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"' \
	'   xmlns:svg="http://www.w3.org/2000/svg"' \
	'   xmlns="http://www.w3.org/2000/svg"' \
	'   xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"' \
	'   xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"' \
	'   width="240mm"' \
	'   height="120mm"' \
	'   viewBox="0 0 240 120"' \
	'   version="1.1"' \
	'   id="svg8"' \
	'   inkscape:version="0.92.4 (unknown)"' \
	'   sodipodi:docname="figure.svg">' \
	'  <defs' \
	'     id="defs2" />' \
	'  <sodipodi:namedview' \
	'     id="base"' \
	'     pagecolor="#ffffff"' \
	'     bordercolor="#666666"' \
	'     borderopacity="1.0"' \
	'     inkscape:pageopacity="0.0"' \
	'     inkscape:pageshadow="2"' \
	'     inkscape:zoom="0.99437388"' \
	'     inkscape:cx="284.27627"' \
	'     inkscape:cy="182.72055"' \
	'     inkscape:document-units="mm"' \
	'     inkscape:current-layer="layer1"' \
	'     showgrid="false"' \
	'     showborder="true"' \
	'     width="200mm"' \
	'     showguides="true"' \
	'     inkscape:guide-bbox="true"' \
	'     inkscape:window-width="2520"' \
	'     inkscape:window-height="995"' \
	'     inkscape:window-x="20"' \
	'     inkscape:window-y="65"' \
	'     inkscape:window-maximized="1">' \
	'    <inkscape:grid' \
	'       type="xygrid"' \
	'       id="grid815"' \
	'       units="mm"' \
	'       spacingx="10"' \
	'       spacingy="10"' \
	'       empspacing="4"' \
	'       dotted="false" />' \
	'  </sodipodi:namedview>' \
	'  <metadata' \
	'     id="metadata5">' \
	'    <rdf:RDF>' \
	'      <cc:Work' \
	'         rdf:about="">' \
	'        <dc:format>image/svg+xml</dc:format>' \
	'        <dc:type' \
	'           rdf:resource="http://purl.org/dc/dcmitype/StillImage" />' \
	'        <dc:title />' \
	'      </cc:Work>' \
	'    </rdf:RDF>' \
	'  </metadata>' \
	'  <g' \
	'     inkscape:label="Layer 1"' \
	'     inkscape:groupmode="layer"' \
	'     id="layer1"' \
	'     transform="translate(0,-177)" />' \
	'</svg>' > "$DIR/figures/$imgname.svg" && inkscape "$DIR/figures/$imgname.svg"
}

menu () {
    case "$prog" in
	""|"dmenu") dmenu -i -l 5 -p "$1" ;;
	"fzf") fzf -i --layout=reverse --prompt "$1" ;;
    esac
}

inktex () {
    [ ! -f "$DIR/figures/$imgname.svg" ] && template || inkscape "$DIR/figures/$imgname.svg"
    svg2pdf "$DIR/figures/$imgname"
}

inkmenu () {
    imglist="$(printf '%s\n' $DIR/figures/*.svg | grep -v "\*.svg")"
    choice="$(printf '%s\n' "remove" "$imglist" | sed '/^$/ d; s/^.*\///; s/\.svg$//' | menu "Select imgs or Type img name: ")"
    [ -z "$choice" ] && exit
    case "$choice" in
	"remove")
	    imgdelete=$(printf '%s\n' "$imglist" | sed '/^$/ d; s/^.*\///; s/\.svg$//' | menu "Delete which figure:")
	    [ -n "$imgdelete" ] && rm $DIR/figures/$imgdelete.* || exit 1
	    ;;
	*)
	    imgname="$choice"
	    inktex
	    ;;
    esac
}

# Main #
[ -z "$DIR" ] && DIR='.'
[ ! -d "$DIR/figures" ] && mkdir -p "$DIR/figures"
[ -z "$imgname" ] && inkmenu || inktex
