#!/bin/sh

# Dependency: inkstyle, dmenu, xdotool

opt=$(dmenu -i -p "Inkscape style option: $(grep 'getopts' $(which inkstyle) | cut -d '"' -f 2)" <&-)
color="$(printf '%s\n' "black" "blue" "green" "red")"
[ -n "$(printf '%s' "$opt" | grep -E "c")" ] &&
    opt=$(printf '%s' "${opt#*c}" "${opt%%c*}") &&
    arg_sc=$(printf '%s\n' "$color" | dmenu -i -p "Stroke color: ") &&
    opt_sc="-c $arg_sc"
[ -n "$(printf '%s' "$opt" | grep -E "C")" ] &&
    opt=$(printf '%s' "${opt#*C}" "${opt%%C*}") &&
    arg_fc=$(printf '%s\n' "$color" | dmenu -i -p "Fill color: ") &&
    opt_fc="-C $arg_fc"
printf '%s' "$opt" | grep '[A-Za-z]' && opt="-$opt" || opt=

inkstyle $opt $opt_sc $opt_fc
xdotool key ctrl+shift+v
