#!/bin/sh
# Dependency: inkscape, pdf2svg, pdfcrop, pdflatex, xclip
# Usage: Typeset latex content into svg/png

TMPDir="/tmp/teximage"
[ ! -d "$TMPDir" ] && mkdir -p "$TMPDir"
texlist="$(printf '%s\n' $TMPDir/*.tex | grep -v "typeset.tex\|\*.tex" | sort -r)"
texnum="$(printf '%s\n' $TMPDir/*.tex | grep -v "typeset.tex\|\*.tex" | wc -l)"
TMPName="doc-$texnum"

tex2svg () {
    cd "$TMPDir" && pdflatex "$1.tex" "$1.pdf" && pdfcrop "$1.pdf" "$1.pdf"
    pdf2svg "$1.pdf" "$1.svg"
    xclip -selection clipboard -t image/x-inkscape-svg -i "$1.svg"
}

svg2png () {
    inkscape --export-dpi 1200 "$1.svg" --export-type=png --export-filename "$1.png"
    xclip -selection clipboard -t image/png -i "$1.png"
}

template () {
    printf '%s\n' \
	'\documentclass[preview]{standalone}' \
	'\usepackage[utf8]{inputenc}' \
	'\usepackage[T1]{fontenc}' \
	'\usepackage{textcomp}' \
	'\usepackage{amsmath, amssymb, amsthm}' \
	'\begin{document}' \
	'' \
	"$1" \
	'' \
	'\end{document}' > "$TMPDir/typeset.tex"
}

opener () {
    [ -n "$TERMINAL" ] && $TERMINAL -e "${EDITOR:-vi}" "$1" || xdg-open "$1"
}

choice=$(printf '%s\n' "new content" "clear" "$texlist" | sed '/^$/ d' | cut -d '/' -f 4 | dmenu -i -l 10 -p "Edit: ")
case "$choice" in
    "new content"|*.tex)
	[ "$choice" = "new content" ] && opener "$TMPDir/$TMPName.tex" || opener "$TMPDir/$choice"
	[ "$choice" = "new content" ] && template "$(cat -u $TMPDir/$TMPName.tex)" || template "$(cat -u $TMPDir/$choice)"
	tex2svg "$TMPDir/typeset"
	[ "$(printf "Yes\\nNo" | dmenu -i -p "Trasform svg image to png?")" = "Yes" ] && svg2png "$TMPDir/typeset"
	;;
    "clear") rm -rf $TMPDir/* ;;
    *) exit ;;
esac
