#!/bin/sh
# Dependency: dmenu/fzf, inkscape, pdf2svg, pdfcrop, pdflatex, xclip
# Usage: Typeset latex content into svg/png

# Options and variables
while getopts ":a:p:o:h" result; do
    case "${result}" in
	h) printf '%s\n' "Arguments:" "-a: Action: 'new content' or 'clear'" "-p: use menu system other than dmenu" "-o: output as 'tex'/'svg'/'png' to clipboard" && exit ;;
	a) choice=${OPTARG} ;;
	p) prog=${OPTARG} ;;
	o) output=${OPTARG} ;;
	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit ;;
    esac
done

TMPDir="/tmp/teximage"
[ ! -d "$TMPDir" ] && mkdir -p "$TMPDir"
texlist="$(printf '%s\n' $TMPDir/*.tex | grep -v "typeset.tex\|\*.tex" | sort -r)"
texnum="$(printf '%s\n' $TMPDir/*.tex | grep -v "typeset.tex\|\*.tex" | wc -l)"
texnum="$(printf '%03d' "$texnum")"
TMPName="doc-$texnum"

menu () {
    case "$prog" in
	"") dmenu -i -l 5 -p "$1" ;;
	"fzf") fzf -i --layout=reverse --prompt "$1" ;;
    esac
}

tex2clip () {
    xclip -selection clipboard < "$1"
}

tex2svg () {
    cd "$TMPDir" && pdflatex "$1.tex" "$1.pdf" && pdfcrop "$1.pdf" "$1.pdf"
    pdf2svg "$1.pdf" "$1.svg"
    xclip -selection clipboard -t image/x-inkscape-svg -i "$1.svg"
}

tex2png () {
    cd "$TMPDir" && pdflatex "$1.tex" "$1.pdf" && pdfcrop "$1.pdf" "$1.pdf"
    pdf2svg "$1.pdf" "$1.svg"
    inkscape --export-dpi 1200 "$1.svg" --export-type=png --export-filename "$1.png"
    xclip -selection clipboard -t image/png -i "$1.png"
}

template () {
    printf '%s\n' \
	'\documentclass[preview]{standalone}' \
	'\usepackage[utf8]{inputenc}' \
	'\usepackage[T1]{fontenc}' \
	'\usepackage{textcomp}' \
	'\usepackage{amsmath, amssymb, amsthm}' \
	'\begin{document}' \
	'' \
	"$1" \
	'' \
	'\end{document}' > "$TMPDir/typeset.tex"
}

opener () {
    case "$prog" in
	"") [ -n "$TERMINAL" ] && $TERMINAL -e "${EDITOR:-vi}" "$1" || ${opener:-xdg-open} "$1" ;;
	"fzf") "${EDITOR:-vi}" "$1" || ${opener:-xdg-open} "$1" ;;
    esac
}

[ -z $choice ] && choice=$(printf '%s\n' "new content" "clear" "$texlist" | sed '/^$/ d; s/^.*\///' | menu "Edit: ")
case "$choice" in
    "new content"|*.tex)
	[ "$choice" = "new content" ] && opener "$TMPDir/$TMPName.tex" || opener "$TMPDir/$choice"
	[ "$choice" = "new content" ] && template "$(cat -u $TMPDir/$TMPName.tex)" || template "$(cat -u $TMPDir/$choice)"
	[ -z $output ] && output=$(printf '%s\n' "tex" "svg" "png" | menu "Output: ")
	case "$output" in
	    "tex") [ "$choice" = "new content" ] && tex2clip "$TMPDir/$TMPName.tex" || tex2clip "$TMPDir/$choice" ;;
	    "svg") tex2svg "$TMPDir/typeset" ;;
	    "png") tex2png "$TMPDir/typeset" ;;
	esac
	;;
    "clear") rm -rf $TMPDir/* ;;
    *) exit ;;
esac
